package FieldsAccumulationRegisterПартииТоваровВПроизводствеRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ПроизводственныйУчастокKey = "ПроизводственныйУчасток_Key"
const Номенклатура = "Номенклатура"
const ОрганизацияKey = "Организация_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОприходования = "ДокументОприходования"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Quantity = "Количество"
const Weight = "Вес"
const Cost = "Стоимость"
const СтоимостьУпр = "СтоимостьУпр"
const СтоимостьБезНДС = "СтоимостьБезНДС"
const OperationCode = "КодОперации"
const СписаниеПартий = "СписаниеПартий"
const НомерКорСтроки = "НомерКорСтроки"
const RecorderType = "Recorder_Type"
const ItemType = "Номенклатура_Type"
const ДокументОприходованияType = "ДокументОприходования_Type"
