package FieldsCatalogДрагоценныеКамни

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const ВидКамняKey = "ВидКамня_Key"
const ГруппаДефекта = "ГруппаДефекта"
const ГруппаЦвета = "ГруппаЦвета"
const КраткоеНаименование = "КраткоеНаименование"
const Рассев = "Рассев"
const РасчетЦеныЗаВес = "РасчетЦеныЗаВес"
const УчетВКаратах = "УчетВКаратах"
const Цвет = "Цвет"
const БИдентификатор = "Б_Идентификатор"
