package FieldsDocumentИнвентаризацияТоваровНаСкладеТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ВесУчет = "ВесУчет"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const КоличествоУчет = "КоличествоУчет"
const ItemKey = "Номенклатура_Key"
const НомерВед = "НомерВед"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Sum = "Сумма"
const СуммаРегл = "СуммаРегл"
const СуммаУчет = "СуммаУчет"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const RetailCost = "ЦенаВРознице"
const ОтклонениеПоКоличеству = "ОтклонениеПоКоличеству"
const ОтклонениеПоВесу = "ОтклонениеПоВесу"
