package FieldsAccumulationRegisterРеализованныеТоварыRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const Сделка = "Сделка"
const ДокументПоставки = "ДокументПоставки"
const Quantity = "Количество"
const Weight = "Вес"
const Выручка = "Выручка"
const RecorderType = "Recorder_Type"
const СделкаType = "Сделка_Type"
const ДокументПоставкиType = "ДокументПоставки_Type"
