package FieldsAccumulationRegisterДвиженияДенежныхСредствRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const ВидДенежныхСредств = "ВидДенежныхСредств"
const ПриходРасход = "ПриходРасход"
const БанковскийСчетКасса = "БанковскийСчетКасса"
const TypeOfMovingMoneyKey = "СтатьяДвиженияДенежныхСредств_Key"
const ДокументДвижения = "ДокументДвижения"
const Контрагент = "Контрагент"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const Сделка = "Сделка"
const ПроектKey = "Проект_Key"
const ДокументПланированияПлатежа = "ДокументПланированияПлатежа"
const Sum = "Сумма"
const СуммаУпр = "СуммаУпр"
const RecorderType = "Recorder_Type"
const БанковскийСчетКассаType = "БанковскийСчетКасса_Type"
const ДокументДвиженияType = "ДокументДвижения_Type"
const КонтрагентType = "Контрагент_Type"
const СделкаType = "Сделка_Type"
const ДокументПланированияПлатежаType = "ДокументПланированияПлатежа_Type"
