package FieldsDocumentПриемИзРемонта

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "ВесДокумента"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const КоличествоДокумента = "КоличествоДокумента"
const КонтрагентKey = "Контрагент_Key"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
const СобственнаяМастерская = "СобственнаяМастерская"
const Изделия = "Изделия"
const Материалы = "Материалы"
