package FieldsCatalogКонтактныеЛица

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const ВидКонтактногоЛица = "ВидКонтактногоЛица"
const ДатаРождения = "ДатаРождения"
const Должность = "Должность"
const Имя = "Имя"
const КоличествоДнейДоНапоминания = "КоличествоДнейДоНапоминания"
const КонтрагентДляОграниченияПравДоступаKey = "КонтрагентДляОграниченияПравДоступа_Key"
const НапоминатьОДнеРождения = "НапоминатьОДнеРождения"
const ОбъектВладелец = "ОбъектВладелец"
const Описание = "Описание"
const Отчество = "Отчество"
const ПользовательДляОграниченияПравДоступаKey = "ПользовательДляОграниченияПравДоступа_Key"
const РольKey = "Роль_Key"
const Фамилия = "Фамилия"
const ОбъектВладелецType = "ОбъектВладелец_Type"
