package FieldsDocumentЗаявкаНаПереоценкуТоваров

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "ВесДокумента"
const ДокументСозданВЮТД = "ДокументСозданВЮТД"
const КоличествоДокумента = "КоличествоДокумента"
const Comment = "Комментарий"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПараметрыОтбораBase64Data = "ПараметрыОтбора_Base64Data"
const ПодразделениеKey = "Подразделение_Key"
const DepartmentKey = "Склад_Key"
const ТипСкидкиНаценкиKey = "ТипСкидкиНаценки_Key"
const ТипЦенKey = "ТипЦен_Key"
const ХозяйственнаяОперацияKey = "ХозяйственнаяОперация_Key"
const НастройкиЗаполненияBase64Data = "НастройкиЗаполнения_Base64Data"
const Goods = "Товары"
const ПараметрыОтбораType = "ПараметрыОтбора_Type"
const НастройкиЗаполненияType = "НастройкиЗаполнения_Type"
const ПараметрыОтбора = "ПараметрыОтбора"
const НастройкиЗаполнения = "НастройкиЗаполнения"
