package FieldsDocumentИнвентаризацияТоваровНаСкладеТоварыВПути

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const Weight = "Вес"
const Quantity = "Количество"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОприходования = "ДокументОприходования"
const КонтрагентKey = "Контрагент_Key"
const ДатаОтправки = "ДатаОтправки"
const ДокументОприходованияType = "ДокументОприходования_Type"
