package FieldsDocumentАктХимическогоАнализаМеталла

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "Вес"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОснование = "ДокументОснование"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const НоменклатураОприходованияМеталлаKey = "НоменклатураОприходованияМеталла_Key"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПробаЛома = "ПробаЛома"
const DepartmentKey = "Склад_Key"
const УказанВесЧистоты = "УказанВесЧистоты"
const ПодразделениеKey = "Подразделение_Key"
const Cost = "Стоимость"
const SumOfDocument = "СуммаДокумента"
const ДокументОснованиеType = "ДокументОснование_Type"
