package FieldsDocumentВозвратТоваровПоставщикуТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДефектKey = "Дефект_Key"
const ДокументПоступления = "ДокументПоступления"
const ЗаказКлиентаKey = "ЗаказКлиента_Key"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const ПроектKey = "Проект_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const ДокументПоступленияType = "ДокументПоступления_Type"
