package FieldsDocumentАктСверки

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ДокументОснование = "ДокументОснование"
const Коментарий = "Коментарий"
const ОтветственныйKey = "Ответственный_Key"
const Сверен = "Сверен"
const SumOfDocument = "СуммаДокумента"
const Goods = "Товары"
const ДокументОснованиеType = "ДокументОснование_Type"
