package FieldsDocumentСписаниеТоваровТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументРезерва = "ДокументРезерва"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Sum = "Сумма"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const OrderKey = "КлючПродажи_Key"
const СкидкаНаценкаKey = "СкидкаНаценка_Key"
const ДокументРезерваType = "ДокументРезерва_Type"
