package FieldsDocumentJournalБанковскиеРасчетныеДокументы

const Ref = "Ref"
const Type = "Type"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Number = "Number"
const Posted = "Posted"
const ВалютаKey = "Валюта_Key"
const OperationType = "ВидОперации"
const ДатаОплаты = "ДатаОплаты"
const ИнформацияKey = "Информация_Key"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const Оплачено = "Оплачено"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const TypeOfMovingMoneyKey = "СтатьяДвиженияДенежныхСредств_Key"
const SumOfDocument = "СуммаДокумента"
const СчетОрганизацииKey = "СчетОрганизации_Key"
const ЧастичнаяОплата = "ЧастичнаяОплата"
const RefType = "Ref_Type"
const ВидОперацииType = "ВидОперации_Type"
