package FieldsDocumentЗаявкаНаПеремещениеТоваров

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "ВесДокумента"
const OperationType = "ВидОперации"
const ДокументСозданВЮТД = "ДокументСозданВЮТД"
const КоличествоДокумента = "КоличествоДокумента"
const Comment = "Комментарий"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const СкладОтправительKey = "СкладОтправитель_Key"
const СкладПолучательKey = "СкладПолучатель_Key"
const SumOfDocument = "СуммаДокумента"
const ТипСкидкиНаценкиKey = "ТипСкидкиНаценки_Key"
const ТипЦенKey = "ТипЦен_Key"
const СпособДоставкиKey = "СпособДоставки_Key"
const ИспользоватьРежимСверки = "ИспользоватьРежимСверки"
const Goods = "Товары"
