package FieldsDocumentЗаявкаНаПеремещениеТоваровТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const ПроцентРозничнойНаценки = "ПроцентРозничнойНаценки"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СтоимостьБезНДС = "СтоимостьБезНДС"
const СтоимостьСНДС = "СтоимостьСНДС"
const Sum = "Сумма"
const СуммаПоступления = "СуммаПоступления"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const ЦенаВРозницеГр = "ЦенаВРозницеГр"
const ЦенаПоступления = "ЦенаПоступления"
