package FieldsDocumentВнутреннийЗаказ

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const АвтоРазмещение = "АвтоРазмещение"
const АвтоРезервирование = "АвтоРезервирование"
const ВидЗаказа = "ВидЗаказа"
const ВремяНапоминания = "ВремяНапоминания"
const ДатаОтгрузки = "ДатаОтгрузки"
const ДокументОснование = "ДокументОснование"
const Заказчик = "Заказчик"
const Comment = "Комментарий"
const НапомнитьОСобытии = "НапомнитьОСобытии"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const ТипДокумента = "ТипДокумента"
const Goods = "Товары"
const ДокументОснованиеType = "ДокументОснование_Type"
const ЗаказчикType = "Заказчик_Type"
