package FieldsCatalogСегментыНоменклатуры

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const СпособФормирования = "СпособФормирования"
const СхемаКомпоновкиДанныхBase64Data = "СхемаКомпоновкиДанных_Base64Data"
const Описание = "Описание"
const ОтветственныйKey = "Ответственный_Key"
const ДатаСоздания = "ДатаСоздания"
const ДатаОчистки = "ДатаОчистки"
const ИмяШаблонаСКД = "ИмяШаблонаСКД"
const БИдентификатор = "Б_Идентификатор"
const БНомерВерсии = "Б_НомерВерсии"
const СхемаКомпоновкиДанныхType = "СхемаКомпоновкиДанных_Type"
const СхемаКомпоновкиДанных = "СхемаКомпоновкиДанных"
