package FieldsDocumentJournalКассовыеДокументы

const Ref = "Ref"
const Type = "Type"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Number = "Number"
const Posted = "Posted"
const ВалютаKey = "Валюта_Key"
const OperationType = "ВидОперации"
const Информация = "Информация"
const КассаKey = "Касса_Key"
const Comment = "Комментарий"
const Контрагент = "Контрагент"
const Оплачено = "Оплачено"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const TypeOfMovingMoneyKey = "СтатьяДвиженияДенежныхСредств_Key"
const SumOfDocument = "СуммаДокумента"
const RefType = "Ref_Type"
const ВидОперацииType = "ВидОперации_Type"
const ИнформацияType = "Информация_Type"
const КонтрагентType = "Контрагент_Type"
