package FieldsDocumentРасходныйКассовыйОрдерТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const СуммаСкидки = "СуммаСкидки"
const ВидТовараККТ = "ВидТовараККТ"
const ТипОплатыТовараККТ = "ТипОплатыТовараККТ"
const СуммаОсн = "СуммаОсн"
const Комитент = "Комитент"
const ТелефонКомитента = "ТелефонКомитента"
const ИННкомитента = "ИННкомитента"
const СуммаОпл = "СуммаОпл"
