package FieldsDocumentСторнированиеОтчетаКомиссионераОПродажахТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументПартииKey = "ДокументПартии_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаВознаграждения = "СуммаВознаграждения"
const СуммаНДС = "СуммаНДС"
const СуммаНДСВознаграждения = "СуммаНДСВознаграждения"
const СуммаНДСПередачи = "СуммаНДСПередачи"
const СуммаПередачи = "СуммаПередачи"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const ЦенаПередачи = "ЦенаПередачи"
