package FieldsDocumentУдалитьНарядЗаказ

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ОрганизацияKey = "Организация_Key"
const КонтрагентKey = "Контрагент_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ОтветственныйKey = "Ответственный_Key"
const Comment = "Комментарий"
const Описание = "Описание"
const ПриемИзделий = "ПриемИзделий"
const ПриемМеталлаВставок = "ПриемМеталлаВставок"
const DepartmentKey = "Склад_Key"
const КоличествоДокумента = "КоличествоДокумента"
const Weight = "ВесДокумента"
const Изделия = "Изделия"
const Услуги = "Услуги"
const Спецификация = "Спецификация"
const Металлы = "Металлы"
const Вставки = "Вставки"
