package FieldsDepartment

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const ВидСклада = "ВидСклада"
const Comment = "Комментарий"
const ПодразделениеKey = "Подразделение_Key"
const РасчетРозничныхЦенПоТорговойНаценке = "РасчетРозничныхЦенПоТорговойНаценке"
const ТипЦенРозничнойТорговлиKey = "ТипЦенРозничнойТорговли_Key"
const СегментИсключаемойНоменклатурыKey = "СегментИсключаемойНоменклатуры_Key"
const ДатаОткрытия = "ДатаОткрытия"
const КУ = "КУ"
const ДиректорKey = "Директор_Key"
const РегионKey = "Регион_Key"
const КоличествоВитрин = "КоличествоВитрин"
const ПлощадьВитрин = "ПлощадьВитрин"
const ПлощадьТорговая = "ПлощадьТорговая"
const НомерСекции = "НомерСекции"
const ФорматМагазинаKey = "ФорматМагазина_Key"
const БИдентификатор = "Б_Идентификатор"
const БНомерВерсии = "Б_НомерВерсии"
