package FieldsDocumentЗаказКлиентаТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ЗначениеУсловияАвтоматическойСкидки = "ЗначениеУсловияАвтоматическойСкидки"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const PercentAutoDiscount = "ПроцентАвтоматическойСкидки"
const PercentManualDiscount = "ПроцентРучнойСкидки"
const SizeKey = "Размер_Key"
const Разместить = "Разместить"
const Резервировать = "Резервировать"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const УсловиеАвтоматическойСкидки = "УсловиеАвтоматическойСкидки"
const Cost = "Цена"
const InstanceKey = "СерияНоменклатуры_Key"
const SumAutoDiscount = "СуммаАвтоматическойСкидки"
const SumManualDiscount = "СуммаРучнойСкидки"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const ЗначениеУсловияАвтоматическойСкидкиType = "ЗначениеУсловияАвтоматическойСкидки_Type"
