package FieldsDocumentJournalСкладскиеДокументы

const Ref = "Ref"
const Type = "Type"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Number = "Number"
const Posted = "Posted"
const ВалютаKey = "Валюта_Key"
const Comment = "Комментарий"
const Контрагент = "Контрагент"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const Подразделение = "Подразделение"
const Склад = "Склад"
const Sum = "Сумма"
const RefType = "Ref_Type"
const КонтрагентType = "Контрагент_Type"
const ПодразделениеType = "Подразделение_Type"
const СкладType = "Склад_Type"
