package FieldsDocumentПоступлениеТоваровУслугТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ЕдиницаИзмеренияKey = "ЕдиницаИзмерения_Key"
const ЗаказКлиентаKey = "ЗаказКлиента_Key"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const Коэф = "Коэф"
const Коэффициент = "Коэффициент"
const НаборKey = "Набор_Key"
const ItemKey = "Номенклатура_Key"
const НомерГТДKey = "НомерГТД_Key"
const НомерНабора = "НомерНабора"
const Паспорт = "Паспорт"
const ПроектKey = "Проект_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const СтранаПроисхожденияKey = "СтранаПроисхождения_Key"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
