package FieldsCatalogТиповыеАнкеты

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const Адресная = "Адресная"
const ВидСправочникаДляЗагрузки = "ВидСправочникаДляЗагрузки"
const Вступление = "Вступление"
const ЗагружатьОбъекты = "ЗагружатьОбъекты"
const МакетАнкетыBase64Data = "МакетАнкеты_Base64Data"
const НаименованиеАнкеты = "НаименованиеАнкеты"
const ВопросыАнкеты = "ВопросыАнкеты"
const МакетАнкетыType = "МакетАнкеты_Type"
const МакетАнкеты = "МакетАнкеты"
