package FieldsCatalogВерсииФайловЭлектронныеПодписи

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ДатаПодписи = "ДатаПодписи"
const ИмяФайлаПодписи = "ИмяФайлаПодписи"
const Comment = "Комментарий"
const КомуВыданСертификат = "КомуВыданСертификат"
const Отпечаток = "Отпечаток"
const ПодписьBase64Data = "Подпись_Base64Data"
const УстановившийПодписьKey = "УстановившийПодпись_Key"
const СертификатBase64Data = "Сертификат_Base64Data"
const ПодписьType = "Подпись_Type"
const СертификатType = "Сертификат_Type"
const Подпись = "Подпись"
const Сертификат = "Сертификат"
