package FieldsDocumentВозвратМатериаловИзПроизводства

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "ВесДокумента"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОснование = "ДокументОснование"
const КоличествоДокумента = "КоличествоДокумента"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const ПроектKey = "Проект_Key"
const DepartmentKey = "Склад_Key"
const ТипДокумента = "ТипДокумента"
const ХозяйственнаяОперацияKey = "ХозяйственнаяОперация_Key"
const ПроизводственныйУчастокKey = "ПроизводственныйУчасток_Key"
const СобственноеПроизводство = "СобственноеПроизводство"
const Goods = "Товары"
const ДокументОснованиеType = "ДокументОснование_Type"
