package FieldsCatalogOrderKey

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const УникальныйИдентификаторПродажи = "УникальныйИдентификаторПродажи"
const TransactionIdСписания = "TransactionIdСписания"
const TransactionIdНачисления = "TransactionIdНачисления"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
const Number = "Номер"
const Date = "Дата"
const OperationType = "ВидОперации"
const MemberCardKey = "ДисконтнаяКарта_Key"
