package FieldsDocumentЧекККМПодарки

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const СкидкаНаценкаKey = "СкидкаНаценка_Key"
const ItemKey = "Номенклатура_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const SizeKey = "Размер_Key"
const Quantity = "Количество"
const Weight = "Вес"
const Cost = "Цена"
const Sum = "Сумма"
const DepartmentKey = "Склад_Key"
const КлючСвязи = "КлючСвязи"
