package FieldsDocumentИзменениеПравДоступа

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const АдресЭлектроннойПочты = "АдресЭлектроннойПочты"
const КонтрагентДоKey = "КонтрагентДо_Key"
const ОрганизацияДоKey = "ОрганизацияДо_Key"
const ДоговорКонтрагентаДоKey = "ДоговорКонтрагентаДо_Key"
const ПравоДоступаДо = "ПравоДоступаДо"
const ОрганизацияKey = "Организация_Key"
const КонтрагентKey = "Контрагент_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ПравоДоступа = "ПравоДоступа"
