package FieldsDocumentПереоценкаВалютныхСредств

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ВзаиморасчетыСКонтрагентами = "ВзаиморасчетыСКонтрагентами"
const ВзаиморасчетыСПодотчетнымиЛицами = "ВзаиморасчетыСПодотчетнымиЛицами"
const ДенежныеСредстваВКассах = "ДенежныеСредстваВКассах"
const ДенежныеСредстваНаБанковскихСчетах = "ДенежныеСредстваНаБанковскихСчетах"
const Comment = "Комментарий"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПоВсемОрганизациям = "ПоВсемОрганизациям"
const ПодразделениеKey = "Подразделение_Key"
const ТипДокумента = "ТипДокумента"
