package FieldsAccumulationRegisterТоварыВОтбореRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const ЗаказКлиента = "ЗаказКлиента"
const DepartmentKey = "Склад_Key"
const КОтбору = "КОтбору"
const Отобрано = "Отобрано"
const ОтобраноВес = "ОтобраноВес"
const RecorderType = "Recorder_Type"
const ЗаказКлиентаType = "ЗаказКлиента_Type"
