package FieldsDocumentРеализацияТоваровУслугТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ЗначениеУсловияАвтоматическойСкидки = "ЗначениеУсловияАвтоматическойСкидки"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const PercentAutoDiscount = "ПроцентАвтоматическойСкидки"
const PercentManualDiscount = "ПроцентРучнойСкидки"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const УсловиеАвтоматическойСкидки = "УсловиеАвтоматическойСкидки"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const SumManualDiscount = "СуммаРучнойСкидки"
const SumAutoDiscount = "СуммаАвтоматическойСкидки"
const ВесВставок = "ВесВставок"
const ЗначениеУсловияАвтоматическойСкидкиType = "ЗначениеУсловияАвтоматическойСкидки_Type"
