package FieldsDocumentРассылкаАнкет

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const АнкетаKey = "Анкета_Key"
const ПервичнаяРассылкаKey = "ПервичнаяРассылка_Key"
const СУведомлениемОПолучении = "СУведомлениемОПолучении"
const ТекстПисьма = "ТекстПисьма"
const УчетнаяЗаписьДляОтправки = "УчетнаяЗаписьДляОтправки"
const ЭлектронныйАдресОтветов = "ЭлектронныйАдресОтветов"
const ЭлектронныйАдресОтветовВстроенныйПочтовыйКлиентKey = "ЭлектронныйАдресОтветовВстроенныйПочтовыйКлиент_Key"
const Вложения = "Вложения"
const Получатели = "Получатели"
const УчетнаяЗаписьДляОтправкиType = "УчетнаяЗаписьДляОтправки_Type"
const ЭлектронныйАдресОтветовType = "ЭлектронныйАдресОтветов_Type"
