package FieldsDocumentАвансовыйОтчетТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ВидДокВходящий = "ВидДокВходящий"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const ДатаСФ = "ДатаСФ"
const ЗаказКлиентаKey = "ЗаказКлиента_Key"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const НомерСФ = "НомерСФ"
const SupplierKey = "Поставщик_Key"
const ПредъявленСФ = "ПредъявленСФ"
const ПроектKey = "Проект_Key"
const ПроцентРозничнойНаценки = "ПроцентРозничнойНаценки"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const СчетФактураKey = "СчетФактура_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const RetailCost = "ЦенаВРознице"
