package FieldsCatalogНастройкиОбменаДаннымиШтрихМ

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const ВидЗагрузкиОтчетов = "ВидЗагрузкиОтчетов"
const ВидОплаты2Key = "ВидОплаты2_Key"
const ВидОплаты3Key = "ВидОплаты3_Key"
const ВидОплаты4Key = "ВидОплаты4_Key"
const ВыгружатьСхемыНакопления = "ВыгружатьСхемыНакопления"
const ИмяФайлаВыгрузки = "ИмяФайлаВыгрузки"
const ИмяФайлаЗагрузки = "ИмяФайлаЗагрузки"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
