package FieldsCatalogФизическиеЛица

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const ДатаРождения = "ДатаРождения"
const Comment = "Комментарий"
const ОсновноеИзображениеKey = "ОсновноеИзображение_Key"
const Пол = "Пол"
const Сотрудник = "Сотрудник"
const МагазинKey = "Магазин_Key"
const Курьер = "Курьер"
const НастройкаДляРаботыKey = "НастройкаДляРаботы_Key"
const ИНН = "ИНН"
const БИдентификатор = "Б_Идентификатор"
const БНомерВерсии = "Б_НомерВерсии"
