package FieldsDocumentОпрос

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Comment = "Комментарий"
const ОпрашиваемоеЛицо = "ОпрашиваемоеЛицо"
const ОтветственныйKey = "Ответственный_Key"
const РассылкаKey = "Рассылка_Key"
const ТиповаяАнкетаKey = "ТиповаяАнкета_Key"
const Вопросы = "Вопросы"
const СоставнойОтвет = "СоставнойОтвет"
const ОпрашиваемоеЛицоType = "ОпрашиваемоеЛицо_Type"
