package FieldsInitialInstance

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const OperationType = "ВидОперации"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const Comment = "Комментарий"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const DepartmentKey = "Склад_Key"
const СуммаВключаетНДС = "СуммаВключаетНДС"
const ОформитьПродажиДатойДокументаПродажи = "ОформитьПродажиДатойДокументаПродажи"
const Взаиморасчеты = "Взаиморасчеты"
const Goods = "Товары"
