package FieldsDocumentГТДИмпортТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументПартии = "ДокументПартии"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const НомерРаздела = "НомерРаздела"
const ПроектKey = "Проект_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СуммаНДС = "СуммаНДС"
const СуммаПошлины = "СуммаПошлины"
const ФактурнаяСтоимость = "ФактурнаяСтоимость"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const ДокументПартииType = "ДокументПартии_Type"
