package FieldsDocumentЗакрытиеПланируемыхПоступленийДенежныхСредств

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const ОтборДатаКон = "ОтборДатаКон"
const ОтборДатаНач = "ОтборДатаНач"
const ОтборКонтрагент = "ОтборКонтрагент"
const ОтборОтветственный = "ОтборОтветственный"
const ОтборЦФО = "ОтборЦФО"
const ОтветственныйKey = "Ответственный_Key"
const ОтветственныйПоступлениеKey = "ОтветственныйПоступление_Key"
const Состояние = "Состояние"
const ТипДокумента = "ТипДокумента"
const ЦФОKey = "ЦФО_Key"
const ПланируемыеПоступленияДС = "ПланируемыеПоступленияДС"
