package FieldsDocumentВводНачальныхОстатковПоРасходамУСНТоварыПроданные

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ПокупательKey = "Покупатель_Key"
const ДоговорСПокупателемKey = "ДоговорСПокупателем_Key"
const SupplierKey = "Поставщик_Key"
const ДоговорСПоставщикомKey = "ДоговорСПоставщиком_Key"
const Quantity = "Количество"
const Weight = "Вес"
const СуммаПоступления = "СуммаПоступления"
const СуммаПродажи = "СуммаПродажи"
const СтатусРасхода = "СтатусРасхода"
const ДокументПродажи = "ДокументПродажи"
const ДокументОприходования = "ДокументОприходования"
const ДокументПродажиType = "ДокументПродажи_Type"
const ДокументОприходованияType = "ДокументОприходования_Type"
