package FieldsCatalogКлючиАналитикиУчетаНоменклатуры

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const ТипНоменклатуры = "ТипНоменклатуры"
const ProbeKey = "Проба_Key"
const TypeKey = "ТипИзделия_Key"
const SizeKey = "Размер_Key"
const КаменьKey = "Камень_Key"
const РассевKey = "Рассев_Key"
const ФормаОгранкиKey = "ФормаОгранки_Key"
const ЦветКамняKey = "ЦветКамня_Key"
const ГруппаЦветаKey = "ГруппаЦвета_Key"
const ГруппаДефектаKey = "ГруппаДефекта_Key"
const Размер1 = "Размер1"
const Размер2 = "Размер2"
const Размер3 = "Размер3"
const MID = "Артикул"
