package FieldsAccumulationRegisterДенежныеСредстваКСписаниюRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ВидДенежныхСредств = "ВидДенежныхСредств"
const БанковскийСчетКасса = "БанковскийСчетКасса"
const ДокументСписания = "ДокументСписания"
const TypeOfMovingMoneyKey = "СтатьяДвиженияДенежныхСредств_Key"
const Sum = "Сумма"
const RecorderType = "Recorder_Type"
const БанковскийСчетКассаType = "БанковскийСчетКасса_Type"
const ДокументСписанияType = "ДокументСписания_Type"
