package FieldsCatalogТоварныеПозиции

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const DeletionMark = "DeletionMark"
const Позиция1 = "Позиция1"
const Позиция2 = "Позиция2"
const Позиция3 = "Позиция3"
const Позиция4 = "Позиция4"
const Позиция5 = "Позиция5"
const Позиция6 = "Позиция6"
const Позиция7 = "Позиция7"
const Позиция1Type = "Позиция1_Type"
const Позиция2Type = "Позиция2_Type"
const Позиция3Type = "Позиция3_Type"
const Позиция4Type = "Позиция4_Type"
const Позиция5Type = "Позиция5_Type"
const Позиция6Type = "Позиция6_Type"
const Позиция7Type = "Позиция7_Type"
