package FieldsDocumentМаркетинговаяАкция

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const НаименованиеАкции = "НаименованиеАкции"
const Описание = "Описание"
const ДатаНачалаДействия = "ДатаНачалаДействия"
const ДатаОкончанияДействия = "ДатаОкончанияДействия"
const Comment = "Комментарий"
const ОтветственныйKey = "Ответственный_Key"
const ДляВсехМагазинов = "ДляВсехМагазинов"
const ДляВсехМагазиновОдноРасписаниеСкидок = "ДляВсехМагазиновОдноРасписаниеСкидок"
const Магазины = "Магазины"
const СкидкиНаценки = "СкидкиНаценки"
const НаборыЗначенийДоступа = "НаборыЗначенийДоступа"
