package FieldsDocumentГТДИмпорт

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ВалютаДокументаKey = "ВалютаДокумента_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДоговорКонтрагентаРеглKey = "ДоговорКонтрагентаРегл_Key"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const КратностьВзаиморасчетов = "КратностьВзаиморасчетов"
const КратностьДокумента = "КратностьДокумента"
const КурсВзаиморасчетов = "КурсВзаиморасчетов"
const КурсДокумента = "КурсДокумента"
const НомерГТДKey = "НомерГТД_Key"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const ТаможенныйСбор = "ТаможенныйСбор"
const ТаможенныйСборВал = "ТаможенныйСборВал"
const ТаможенныйШтраф = "ТаможенныйШтраф"
const ТаможенныйШтрафВал = "ТаможенныйШтрафВал"
const ТипДокумента = "ТипДокумента"
const Разделы = "Разделы"
const Goods = "Товары"
