package FieldsDocumentКлассификацияПокупателейПоСтадиямВзаимоотношений

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const XКлассКон = "XКлассКон"
const XКлассНач = "XКлассНач"
const YКлассКон = "YКлассКон"
const YКлассНач = "YКлассНач"
const ZКлассКон = "ZКлассКон"
const ZКлассНач = "ZКлассНач"
const ДатаОкончания = "ДатаОкончания"
const КоличествоПериодовАнализа = "КоличествоПериодовАнализа"
const Comment = "Комментарий"
const Периодичность = "Периодичность"
const РазовыйПокупательКон = "РазовыйПокупательКон"
const РазовыйПокупательНач = "РазовыйПокупательНач"
const ТаблицаРаспределенияКонтрагентов = "ТаблицаРаспределенияКонтрагентов"
