package FieldsAccumulationRegisterТоварыВНеавтоматизированныхТорговыхТочкахRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const DepartmentKey = "Склад_Key"
const RetailCost = "ЦенаВРознице"
const Quantity = "Количество"
const Weight = "Вес"
const RecorderType = "Recorder_Type"
