package FieldsDocumentВозвратПродукцииВПроизводствоТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ЗаказКлиентаKey = "ЗаказКлиента_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const СтоимостьРабот = "СтоимостьРабот"
const СтоимостьВставок = "СтоимостьВставок"
const СтоимостьМеталла = "СтоимостьМеталла"
const СуммаНДСВставок = "СуммаНДСВставок"
const СуммаНДСМеталла = "СуммаНДСМеталла"
const СуммаНДСРабот = "СуммаНДСРабот"
const ДефектKey = "Дефект_Key"
const ВесВставок = "ВесВставок"
