package FieldsCatalogКупоны

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const ПроцентСкидки = "ПроцентСкидки"
const СуммаСкидки = "СуммаСкидки"
const Тираж = "Тираж"
const СкидкаСуммой = "СкидкаСуммой"
const ИдентификаторДляWeb = "ИдентификаторДляWeb"
const МаксимальныйПроцентОтСуммыПокупки = "МаксимальныйПроцентОтСуммыПокупки"
const ИспользованиеНесколькихКупоновЭтогоВида = "ИспользованиеНесколькихКупоновЭтогоВида"
const ИспользованиеСДругимиКупонами = "ИспользованиеСДругимиКупонами"
