package FieldsCatalogГруппыДоступа

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const ПрофильKey = "Профиль_Key"
const ПользовательKey = "Пользователь_Key"
const Описание = "Описание"
const ОтветственныйKey = "Ответственный_Key"
const ОсновнаяГруппаДоступаПоставляемогоПрофиля = "ОсновнаяГруппаДоступаПоставляемогоПрофиля"
const РазрешениеНаПросмотрЗакупочнойЦены = "РазрешениеНаПросмотрЗакупочнойЦены"
const Пользователи = "Пользователи"
const ВидыДоступа = "ВидыДоступа"
const ЗначенияДоступа = "ЗначенияДоступа"
const ДоступПоПодсистемам = "ДоступПоПодсистемам"
