package FieldsAccumulationRegisterГрафикПлатежейRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ОрганизацияKey = "Организация_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ВидДоговораКонтрагента = "ВидДоговораКонтрагента"
const ДатаДолга = "ДатаДолга"
const Оплачено = "Оплачено"
const НачисленДолг = "НачисленДолг"
const Долг = "Долг"
const Аванс = "Аванс"
const ОплаченоУпр = "ОплаченоУпр"
const НачисленДолгУпр = "НачисленДолгУпр"
const ДолгУпр = "ДолгУпр"
const АвансУпр = "АвансУпр"
const RecorderType = "Recorder_Type"
