package FieldsCatalogЕдиницыИзмерения

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const Owner = "Owner"
const DeletionMark = "DeletionMark"
const Weight = "Вес"
const ЕдиницаПоКлассификаторуKey = "ЕдиницаПоКлассификатору_Key"
const Коэффициент = "Коэффициент"
const Объем = "Объем"
const БИдентификатор = "Б_Идентификатор"
const БНомерВерсии = "Б_НомерВерсии"
const OwnerType = "Owner_Type"
