package FieldsMemberCard

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const Email = "Email"
const Адрес = "Адрес"
const Бонусная = "Бонусная"
const MemberCardTypeKey = "ВидДисконтнойКарты_Key"
const ДатаРождения = "ДатаРождения"
const Накопительная = "Накопительная"
const Number = "Номер"
const Sum = "Сумма"
const СхемаНакопительныхСкидокKey = "СхемаНакопительныхСкидок_Key"
const Телефон = "Телефон"
const ТипДисконтнойКарты = "ТипДисконтнойКарты"
const ФИО = "ФИО"
const ВладелецКарты = "ВладелецКарты"
const Пол = "Пол"
const КонтрагентKey = "Контрагент_Key"
const ДатаАнкеты = "ДатаАнкеты"
const СогласиеНаСМСРассылку = "СогласиеНаСМСРассылку"
const СогласиеНаПочтовуюРассылку = "СогласиеНаПочтовуюРассылку"
const ВладелецКартыType = "ВладелецКарты_Type"
