package FieldsDocumentПоступлениеДопРасходовТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументПартии = "ДокументПартии"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const ПроектKey = "Проект_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const СуммаРаспределения = "СуммаРаспределения"
const СуммаТовара = "СуммаТовара"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const ДокументПартииType = "ДокументПартии_Type"
