package FieldsDocumentПоступлениеТоваровУслугВНеавтоматизированнуюТорговуюТочкуТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ЕдиницаИзмеренияKey = "ЕдиницаИзмерения_Key"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const Коэф = "Коэф"
const Коэффициент = "Коэффициент"
const ItemKey = "Номенклатура_Key"
const Паспорт = "Паспорт"
const ПроектKey = "Проект_Key"
const ПроцентРозничнойНаценки = "ПроцентРозничнойНаценки"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const RetailCost = "ЦенаВРознице"
const ЦенаВРозницеГр = "ЦенаВРозницеГр"
