package FieldsDocumentДенежныйЧек

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ВалютаДокументаKey = "ВалютаДокумента_Key"
const ДатаОплаты = "ДатаОплаты"
const КассаKey = "Касса_Key"
const Comment = "Комментарий"
const Оплачено = "Оплачено"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const TypeOfMovingMoneyKey = "СтатьяДвиженияДенежныхСредств_Key"
const SumOfDocument = "СуммаДокумента"
const СчетОрганизацииKey = "СчетОрганизации_Key"
const ТипДокумента = "ТипДокумента"
