package FieldsDocumentОприходованиеТоваровТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const Паспорт = "Паспорт"
const ПроцентРозничнойНаценки = "ПроцентРозничнойНаценки"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Sum = "Сумма"
const СуммаРегл = "СуммаРегл"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const RetailCost = "ЦенаВРознице"
const ЦенаВРозницеГр = "ЦенаВРозницеГр"
