package FieldsDocumentИнтернетЗаказТоварыИнтернетЗаказа

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ItemKey = "Номенклатура_Key"
const SizeKey = "Размер_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Quantity = "Количество"
const Weight = "Вес"
const Cost = "Цена"
const Sum = "Сумма"
const СтавкаНДС = "СтавкаНДС"
const СуммаНДС = "СуммаНДС"
const ПодобранПолностью = "ПодобранПолностью"
const Отказ = "Отказ"
