package FieldsCatalogИдентификаторыОбъектовМетаданных

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const ParentKey = "Parent_Key"
const DeletionMark = "DeletionMark"
const ПорядокКоллекции = "ПорядокКоллекции"
const Имя = "Имя"
const Синоним = "Синоним"
const ПолноеИмя = "ПолноеИмя"
const ПолныйСиноним = "ПолныйСиноним"
const БезДанных = "БезДанных"
const ЗначениеПустойСсылки = "ЗначениеПустойСсылки"
const КлючОбъектаМетаданныхBase64Data = "КлючОбъектаМетаданных_Base64Data"
const НоваяСсылкаKey = "НоваяСсылка_Key"
const ЗначениеПустойСсылкиType = "ЗначениеПустойСсылки_Type"
const КлючОбъектаМетаданныхType = "КлючОбъектаМетаданных_Type"
const КлючОбъектаМетаданных = "КлючОбъектаМетаданных"
