package FieldsDocumentУдалитьНарядЗаказИзделия

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ItemKey = "Номенклатура_Key"
const Quantity = "Количество"
const Weight = "Вес"
const SizeKey = "Размер_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const TypeKey = "ТипИзделия_Key"
const ProbeKey = "Проба_Key"
const Комментарии = "Комментарии"
const ВесБезВставок = "ВесБезВставок"
const НомерСтрокиТЧ = "НомерСтрокиТЧ"
const InstanceKey = "СерияНоменклатуры_Key"
