package FieldsCatalogДоговорыРассрочки

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const OwnerKey = "Owner_Key"
const DeletionMark = "DeletionMark"
const Date = "Дата"
const Number = "Номер"
const МесяцевРассрочки = "МесяцевРассрочки"
const СуммаЕжемесячногоПлатежа = "СуммаЕжемесячногоПлатежа"
const СуммаРассрочки = "СуммаРассрочки"
const СуммаПокупки = "СуммаПокупки"
const СуммаПервоначальногоВзноса = "СуммаПервоначальногоВзноса"
