package FieldsDocumentИнформационноеСообщение

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Email = "Email"
const ДатаРождения = "ДатаРождения"
const КлючПродажKey = "КлючПродаж_Key"
const SumOfDocument = "СуммаДокумента"
const Телефон = "Телефон"
const ФИО = "ФИО"
const ОтказОтПредъявленияУЛ = "ОтказОтПредъявленияУЛ"
const Пол = "Пол"
const ДокументУдостоверяющийЛичность = "ДокументУдостоверяющийЛичность"
const MemberCardKey = "ДисконтнаяКарта_Key"
const ДокументСозданВЮТД = "ДокументСозданВЮТД"
const ДокументВидKey = "ДокументВид_Key"
const ДокументСерия = "ДокументСерия"
const ДокументНомер = "ДокументНомер"
const ДокументДатаВыдачи = "ДокументДатаВыдачи"
const ДокументКемВыдан = "ДокументКемВыдан"
const ДокументКодПодразделения = "ДокументКодПодразделения"
const КонтрагентKey = "Контрагент_Key"
const СуммаДокументаБезНал = "СуммаДокументаБезНал"
