package FieldsCatalogБанковскиеСчета

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const Owner = "Owner"
const DeletionMark = "DeletionMark"
const БанкKey = "Банк_Key"
const БанкДляРасчетовKey = "БанкДляРасчетов_Key"
const ВалютаДенежныхСредствKey = "ВалютаДенежныхСредств_Key"
const ВидСчета = "ВидСчета"
const ДатаЗакрытия = "ДатаЗакрытия"
const ДатаОткрытия = "ДатаОткрытия"
const КонтрагентДляОграниченияПравДоступаKey = "КонтрагентДляОграниченияПравДоступа_Key"
const МесяцПрописью = "МесяцПрописью"
const НомерИДатаРазрешения = "НомерИДатаРазрешения"
const НомерСчета = "НомерСчета"
const ОрганизацияДляОграниченияПравДоступаKey = "ОрганизацияДляОграниченияПравДоступа_Key"
const СуммаБезКопеек = "СуммаБезКопеек"
const ТекстКорреспондента = "ТекстКорреспондента"
const ТекстНазначения = "ТекстНазначения"
const OwnerType = "Owner_Type"
