package FieldsDocumentАвансовыйОтчетПрочее

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ВидДокВходящий = "ВидДокВходящий"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const ДатаСФ = "ДатаСФ"
const Заказ = "Заказ"
const ItemKey = "Номенклатура_Key"
const НоменклатурнаяГруппаKey = "НоменклатурнаяГруппа_Key"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const НомерСФ = "НомерСФ"
const ПодразделениеKey = "Подразделение_Key"
const SupplierKey = "Поставщик_Key"
const ПредъявленСФ = "ПредъявленСФ"
const ПроектKey = "Проект_Key"
const Содержание = "Содержание"
const СтавкаНДС = "СтавкаНДС"
const СтатьяЗатратKey = "СтатьяЗатрат_Key"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const СчетФактураKey = "СчетФактура_Key"
const ЗаказType = "Заказ_Type"
