package FieldsDocumentJournalПроизводственныеДокументы

const Ref = "Ref"
const Type = "Type"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Number = "Number"
const Posted = "Posted"
const ВалютаДокументаKey = "ВалютаДокумента_Key"
const Weight = "Вес"
const Quantity = "Количество"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const DepartmentKey = "Склад_Key"
const Sum = "Сумма"
const RefType = "Ref_Type"
