package FieldsDocumentКассовыйЧекКоррекции

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ОрганизацияKey = "Организация_Key"
const КассаККМKey = "КассаККМ_Key"
const SumOfDocument = "СуммаДокумента"
const СтавкаНДС = "СтавкаНДС"
const ТипКоррекции = "ТипКоррекции"
const ТипРасчета = "ТипРасчета"
const ОтветственныйKey = "Ответственный_Key"
const Comment = "Комментарий"
const NumberKKT = "НомерЧекаККМ"
const Предписание = "Предписание"
const ПробитЧекНаККТ = "ПробитЧекНаККТ"
const ОснованиеДляКоррекции = "ОснованиеДляКоррекции"
const ДатаДокументаОснования = "ДатаДокументаОснования"
const НомерДокументаОснования = "НомерДокументаОснования"
const ПредставлениеОснования = "ПредставлениеОснования"
const СуммаНДС = "СуммаНДС"
const GungNumber = "НомерСменыККМ"
const ТипСистемыНалогообложенияKey = "ТипСистемыНалогообложения_Key"
const Payments = "Оплата"
const ОснованиеДляКоррекцииType = "ОснованиеДляКоррекции_Type"
