package FieldsPosting

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Weight = "ВесДокумента"
const ДокументОснование = "ДокументОснование"
const ДокументСозданВЮТД = "ДокументСозданВЮТД"
const ИнвентаризацияТоваровНаСкладеKey = "ИнвентаризацияТоваровНаСкладе_Key"
const КоличествоДокумента = "КоличествоДокумента"
const Comment = "Комментарий"
const ОрганизацияKey = "Организация_Key"
const Основание = "Основание"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const DepartmentKey = "Склад_Key"
const SumOfDocument = "СуммаДокумента"
const СуммаДокументаРегл = "СуммаДокументаРегл"
const ТипДокумента = "ТипДокумента"
const ТипЦенKey = "ТипЦен_Key"
const ХозяйственнаяОперацияKey = "ХозяйственнаяОперация_Key"
const ВыставкаОстатки = "ВыставкаОстатки"
const Goods = "Товары"
const Сертификаты = "Сертификаты"
const ДокументОснованиеType = "ДокументОснование_Type"
