package FieldsAccumulationRegisterТоварыВПутиRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОприходования = "ДокументОприходования"
const Quantity = "Количество"
const Weight = "Вес"
const RecorderType = "Recorder_Type"
const ДокументОприходованияType = "ДокументОприходования_Type"
