package FieldsDocumentДокументРасчетовСКонтрагентом

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ДатаВходящегоДокумента = "ДатаВходящегоДокумента"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДокументОснованиеKey = "ДокументОснование_Key"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const НомерВходящегоДокумента = "НомерВходящегоДокумента"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
const OperationType = "ВидОперации"
const SumOfDocument = "СуммаДокумента"
