package FieldsDocumentСторнированиеОтчетаКомитентуОПродажахТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументПоступления = "ДокументПоступления"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const ОтчетКомитентуKey = "ОтчетКомитенту_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const Sum = "Сумма"
const СуммаВознаграждения = "СуммаВознаграждения"
const СуммаНДСВознаграждения = "СуммаНДСВознаграждения"
const СуммаПоступления = "СуммаПоступления"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const ЦенаПоступления = "ЦенаПоступления"
const ДокументПоступленияType = "ДокументПоступления_Type"
