package FieldsCatalogХранилищеДополнительнойИнформации

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const DeletionMark = "DeletionMark"
const ВидДанных = "ВидДанных"
const ЗначениеРазделенияДоступаKey = "ЗначениеРазделенияДоступа_Key"
const ИДФайлаПочтовогоПисьма = "ИДФайлаПочтовогоПисьма"
const ИмяФайла = "ИмяФайла"
const Объект = "Объект"
const ХранилищеBase64Data = "Хранилище_Base64Data"
const ВыгружатьНаСайт = "ВыгружатьНаСайт"
const ОбъектType = "Объект_Type"
const ХранилищеType = "Хранилище_Type"
const Хранилище = "Хранилище"
