package FieldsDocumentАктСверкиТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const MID = "Артикул"
const Weight = "Вес"
const ЗаказКлиентаKey = "ЗаказКлиента_Key"
const Quantity = "Количество"
const Коэф = "Коэф"
const НаборKey = "Набор_Key"
const Найдено = "Найдено"
const ItemKey = "Номенклатура_Key"
const НомерНабора = "НомерНабора"
const Паспорт = "Паспорт"
const ПроектKey = "Проект_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const Период = "Период"
