package FieldsDocumentВозвратТоваровОтПокупателяТовары

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const Weight = "Вес"
const ДокументОприходования = "ДокументОприходования"
const ДокументПартии = "ДокументПартии"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const ItemKey = "Номенклатура_Key"
const Паспорт = "Паспорт"
const PercentManualDiscount = "ПроцентРучнойСкидки"
const SizeKey = "Размер_Key"
const Себестоимость = "Себестоимость"
const СебестоимостьБезНДС = "СебестоимостьБезНДС"
const СебестоимостьУпр = "СебестоимостьУпр"
const InstanceKey = "СерияНоменклатуры_Key"
const SumManualDiscount = "СуммаРучнойСкидки"
const DepartmentKey = "Склад_Key"
const СтавкаНДС = "СтавкаНДС"
const СтатусПартии = "СтатусПартии"
const Sum = "Сумма"
const СуммаНДС = "СуммаНДС"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const Cost = "Цена"
const OrderKey = "КлючПродажи_Key"
const ДокументОприходованияType = "ДокументОприходования_Type"
const ДокументПартииType = "ДокументПартии_Type"
