package FieldsDocumentРеестрСчетов

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ДатаАккредитива = "ДатаАккредитива"
const ДатаЗакрытия = "ДатаЗакрытия"
const ДокументОснованиеKey = "ДокументОснование_Key"
const ИсполняющийБанкKey = "ИсполняющийБанк_Key"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const НомерАккредитива = "НомерАккредитива"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const СуммаАккредитива = "СуммаАккредитива"
const СчетКонтрагентаKey = "СчетКонтрагента_Key"
const СчетОрганизацииKey = "СчетОрганизации_Key"
const Реестр = "Реестр"
