package FieldsDocumentПланПродажПоСалонам

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ПлановыйПериод = "ПлановыйПериод"
const СуммаПлана = "СуммаПлана"
const Comment = "Комментарий"
const ПоДням = "ПоДням"
const ДетализацияПлана = "ДетализацияПлана"
const КалендарьПланаKey = "КалендарьПлана_Key"
const Салоны = "Салоны"
const ДниПоГрафику = "ДниПоГрафику"
