package FieldsDocumentJournalДокументыКонтрагентов

const Ref = "Ref"
const Type = "Type"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Number = "Number"
const Posted = "Posted"
const ВалютаKey = "Валюта_Key"
const Weight = "Вес"
const OperationType = "ВидОперации"
const Информация = "Информация"
const Quantity = "Количество"
const Comment = "Комментарий"
const Контрагент = "Контрагент"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПодразделениеKey = "Подразделение_Key"
const Sum = "Сумма"
const RefType = "Ref_Type"
const ВидОперацииType = "ВидОперации_Type"
const ИнформацияType = "Информация_Type"
const КонтрагентType = "Контрагент_Type"
