package FieldsDocumentДоверенность

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ДатаДействия = "ДатаДействия"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ДолжностьKey = "Должность_Key"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const НаПолучениеОт = "НаПолучениеОт"
const ОрганизацияKey = "Организация_Key"
const ОтветственныйKey = "Ответственный_Key"
const ПоДокументу = "ПоДокументу"
const ПодразделениеKey = "Подразделение_Key"
const Сделка = "Сделка"
const СтруктурнаяЕдиницаKey = "СтруктурнаяЕдиница_Key"
const ФизЛицоKey = "ФизЛицо_Key"
const Goods = "Товары"
const СделкаType = "Сделка_Type"
