package FieldsDocumentУстановкаЦенНоменклатуры

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const ВыбГруппаKey = "ВыбГруппа_Key"
const ДокументОснование = "ДокументОснование"
const ДокументСозданВЮТД = "ДокументСозданВЮТД"
const Информация = "Информация"
const Comment = "Комментарий"
const НеПроводитьНулевыеЗначения = "НеПроводитьНулевыеЗначения"
const ОтветственныйKey = "Ответственный_Key"
const ПараметрыОтбораBase64Data = "ПараметрыОтбора_Base64Data"
const РегистрацияЦенПоСегментамНоменклатуры = "РегистрацияЦенПоСегментамНоменклатуры"
const НастройкиЗаполненияBase64Data = "НастройкиЗаполнения_Base64Data"
const ТипыЦен = "ТипыЦен"
const Goods = "Товары"
const ДокументОснованиеType = "ДокументОснование_Type"
const ПараметрыОтбораType = "ПараметрыОтбора_Type"
const НастройкиЗаполненияType = "НастройкиЗаполнения_Type"
const ПараметрыОтбора = "ПараметрыОтбора"
const НастройкиЗаполнения = "НастройкиЗаполнения"
