package FieldsCatalogТипыСкидокНаценок

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const DeletionMark = "DeletionMark"
const ВалютаKey = "Валюта_Key"
const ВидСкидки = "ВидСкидки"
const ДляВсейНоменклатуры = "ДляВсейНоменклатуры"
const ДляВсехПолучателей = "ДляВсехПолучателей"
const ЗначениеУсловия = "ЗначениеУсловия"
const ОбщееВремяНачала = "ОбщееВремяНачала"
const ОбщееВремяОкончания = "ОбщееВремяОкончания"
const ОграничениеСкидкиНаценки = "ОграничениеСкидкиНаценки"
const ПоДнямНедели = "ПоДнямНедели"
const ПроцентСкидкиНаценки = "ПроцентСкидкиНаценки"
const Условие = "Условие"
const ВремяПоДнямНедели = "ВремяПоДнямНедели"
const ЗначениеУсловияType = "ЗначениеУсловия_Type"
