package FieldsCatalogНастройкиОтчетов

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Description = "Description"
const Code = "Code"
const ParentKey = "Parent_Key"
const IsFolder = "IsFolder"
const DeletionMark = "DeletionMark"
const НаименованиеОтчета = "НаименованиеОтчета"
const НастройкаДляАвтосохранения = "НастройкаДляАвтосохранения"
const НастройкаПоУмолчанию = "НастройкаПоУмолчанию"
const НастройкиОтчетаBase64Data = "НастройкиОтчета_Base64Data"
const НастройкиПостроителяBase64Data = "НастройкиПостроителя_Base64Data"
const ГруппыНастроекИПользователи = "ГруппыНастроекИПользователи"
const НастройкиОтчетаType = "НастройкиОтчета_Type"
const НастройкиПостроителяType = "НастройкиПостроителя_Type"
const НастройкиОтчета = "НастройкиОтчета"
const НастройкиПостроителя = "НастройкиПостроителя"
