package FieldsAccumulationRegisterПродажиПоДисконтнымКартамRecordType

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const MemberCardKey = "ДисконтнаяКарта_Key"
const ItemKey = "Номенклатура_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ДокументПродажи = "ДокументПродажи"
const Sum = "Сумма"
const Quantity = "Количество"
const Weight = "Вес"
const RecorderType = "Recorder_Type"
const ДокументПродажиType = "ДокументПродажи_Type"
