package FieldsDocumentТелемаркетинг

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const АвторKey = "Автор_Key"
const Основание = "Основание"
const Comment = "Комментарий"
const Важность = "Важность"
const ПроектKey = "Проект_Key"
const СостояниеСобытия = "СостояниеСобытия"
const ОтветственныйKey = "Ответственный_Key"
const Тема = "Тема"
const ТиповаяАнкетаKey = "ТиповаяАнкета_Key"
const ВремяНапоминания = "ВремяНапоминания"
const НапомнитьОСобытии = "НапомнитьОСобытии"
const Участники = "Участники"
const ОснованиеType = "Основание_Type"
