package FieldsDocumentРегистрацияНаСайте

const Key = "Ref_Key"
const DataVersion = "DataVersion"
const Number = "Number"
const Date = "Date"
const DeletionMark = "DeletionMark"
const Posted = "Posted"
const Наименование = "Наименование"
const НаименованиеПолное = "НаименованиеПолное"
const ИНН = "ИНН"
const КПП = "КПП"
const ФИО = "ФИО"
const Телефон = "Телефон"
const АдресЭлектроннойПочты = "АдресЭлектроннойПочты"
const Comment = "Комментарий"
const КонтрагентKey = "Контрагент_Key"
const Регистрация = "Регистрация"
const ОрганизацияKey = "Организация_Key"
const ДоговорКонтрагентаKey = "ДоговорКонтрагента_Key"
const ПравоДоступа = "ПравоДоступа"
