package FieldsDocumentВводНачальныхОстатковПоРасходамУСНТоварыНаОстатках

const Key = "Ref_Key"
const LineNumber = "LineNumber"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const SupplierKey = "Поставщик_Key"
const ДоговорСПоставщикомKey = "ДоговорСПоставщиком_Key"
const Quantity = "Количество"
const Weight = "Вес"
const СуммаПоступления = "СуммаПоступления"
const СтатусРасхода = "СтатусРасхода"
const ДокументОприходования = "ДокументОприходования"
const СуммаПоступленияБезНДС = "СуммаПоступленияБезНДС"
const ДокументОприходованияType = "ДокументОприходования_Type"
