package FieldsProductActionDocument

const Recorder = "Recorder"
const Period = "Period"
const LineNumber = "LineNumber"
const Active = "Active"
const RecordType = "RecordType"
const ItemKey = "Номенклатура_Key"
const InstanceKey = "СерияНоменклатуры_Key"
const ХарактеристикаНоменклатурыKey = "ХарактеристикаНоменклатуры_Key"
const SizeKey = "Размер_Key"
const ОрганизацияKey = "Организация_Key"
const DepartmentKey = "Склад_Key"
const ДокументОприходования = "ДокументОприходования"
const СтатусПартии = "СтатусПартии"
const КачествоKey = "Качество_Key"
const Quantity = "Количество"
const Weight = "Вес"
const Cost = "Стоимость"
const СтоимостьУпр = "СтоимостьУпр"
const СтоимостьБезНДС = "СтоимостьБезНДС"
const OperationCode = "КодОперации"
const СписаниеПартий = "СписаниеПартий"
const НомерКорСтроки = "НомерКорСтроки"
const RecorderType = "Recorder_Type"
const ДокументОприходованияType = "ДокументОприходования_Type"
